service: hello-world
frameworkVersion: "2"

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    hello:
      name: hello
      definition:
        Comment: hello world example
        StartAt: SayHello
        States:
          SayHello:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true
